### ISSUE TITLE
OCAT isn't logging anything for Uplay and Stream

### ISSUE THREAD

**Issue by whitefox24** [GPUOpen-Tools/OCAT#21] opened 2017-07-14 19:06 UTC
Hey, so I've been benchmarking a few games on a test system and it so happened that OCAT didn't log anything after I hit the recording hotkey. I've attached my current PRESENTMON files 
I think it might have to do something with the code line... "GetProcessID FromName - Process no found"

Thoughts?
![uplay benchmark issue](https://user-images.githubusercontent.com/30182234/28226975-082da974-68a6-11e7-9ccd-e0c0ec1b49ac.JPG)

**Comment by amddb** [comment] 2017-07-17 08:36
Hey @whitefox24 , I can't reproduce this issue on my machine. Can you do me a favor and try to get recording data from PresentMon (https://github.com/GameTechDev/PresentMon/releases) directly?
Especially the fixed bugs from their latest release look like they would fix your issue.

**Comment by rys** [comment] 2018-12-17 16:05
Closing due to issue age. Please create a new issue if you're still experiencing issues with game compatibility.

**Closed by rys** 2018-12-17 16:05 UTC
Labels: bug, not verified
