### ISSUE TITLE
OCAT Crashes when clicking Start (System.Runtime.InteropServices.SEHException)

### ISSUE THREAD

**Issue by stevendevit** [GPUOpen-Tools/OCAT#23] opened 2017-08-06 21:35 UTC
Any idea what's happening?

![preview](https://user-images.githubusercontent.com/20980018/29007290-e879a6fc-7aff-11e7-88f7-715ea34c8e18.PNG)

**Comment by amddb** [comment] 2017-08-07 09:15
Hey @HaTanka this is the same issue that was reported here: https://github.com/GPUOpen-Tools/OCAT/issues/17. Given that I can't reproduce it on my side, can you provide a little bit more information, please?

1. Which version of OCAT are you running? Does that happen with v1.0.0 as well?
2. Did you have OCAT on your machine previously? e.g. did you uninstall the old version before installing the later version?

I am suspecting, that the underlying call to CreateProcess fails (it is spawning the GlobalHook process).
So I'd be interested in the following stuff as well:
3. Can you check if CreateProcess in GlobalHook::StartGlobalHookProcess resolves to CreateProcessA or CreateProcessW?
4. Does your installation path (/ local repository) contain spaces? Or other special characters?

**Comment by HaTanka** [comment] 2017-08-08 17:34
@amddb Hey, I did find the bug. It seems that _directories[DIR BIN] never gets assigned.
So I hardcoded the Bin Folder Path and just worked perfectly!

![1](https://user-images.githubusercontent.com/20980018/29085518-d98fd6c2-7c6f-11e7-9945-c51d6c21ac9c.PNG)

By the way, when I try to capture a single application I get this error

![2](https://user-images.githubusercontent.com/20980018/29085651-3294a59a-7c70-11e7-8769-d02b84f6cddf.PNG)

**Comment by amddb** [comment] 2017-08-09 09:16
Hey @HaTanka , first of all: Thanks for investigating that issue further! I'll try to find a proper solution (at least OCAT should give a propper error message when encountering your problem instead of crashing). 
Your second issue should be fixed in the upcoming release. Please file a new bug, if it persists :)

Although, OCAT normally doesn't get through proper anti cheat systems anyway, I can't give you any guarantees for not getting banned. Use it at your own risk!

**Comment by farkasg75** [comment] 2017-08-12 12:49
With the last version I have a same problem too, but I find the part of code, where I runs out to crash in the Wrapper.cpp:

void Wrapper::OverlayWrapper::StartCaptureExe(String^ exe, String^ cmdArgs)
{
  std::wstring exeW = msclr::interop::marshal_as<std::wstring>(exe);
  std::wstring cmdArgsW = msclr::interop::marshal_as<std::wstring>(cmdArgs);
  **overlayInterface_->StartProcess(exeW, cmdArgsW);**
}
What is missing in my system, or what is blocking to start overlaying?

**Comment by HaTanka** [comment] 2017-08-13 21:00
@amddb no problem! 

Hey, will OCAT support DirectX9? As you may know most games use DirectX9, so it would be a really good feature

**Comment by amddb** [comment] 2017-08-14 06:21
@farkasg75 There has been no fix for that issue in the 1.1.0 release, sorry. The crash is most likely related to OCAT not finding the binary directory, as the findings by @HaTanka suggest. Here's what happens in that case: 

1. Once OCAT enables the overlay injection it tries to load the GlobalHook.exe.
2. It failed to find the binary directory (OCAT-Install-Directory/Bin), where all of the necessary DLLs and executables are stored
3. The call to CreateProcess fails internally, which doesn't result in an error code.
4. OCAT crashes

So I am trying to implement a more reliable way to retrieve the binary directory.
Additionally I added some precautions, so OCAT should not crash in these cases anymore.

If you are familiar with C++ development, you could try to use the workaround from @HaTanka in the meantime.

@HaTanka I'd rather invest some time into bug fixes at the moment. But you are not the first one to mention DirectX 9 support. Can you please open a new feature request for that?

**Closed** 2018-12-17 16:02 UTC
Labels: bug, not verified
