### ISSUE TITLE
Windows 10 Creators Update

### ISSUE THREAD

**Issue by jarredwalton** [GPUOpen-Tools/OCAT#9] opened 2017-04-19 19:44 UTC
Something seems to have changed quite a bit with Creators Update. OCAT no longer creates output files when testing games -- Doom Vulkan specifically is a problem, which is the only games where I currently use OCAT. The FPS view in the corner seems to work fine, and at the end of a benchmark session it will show results, but you only have a second or two to write those down.

**Comment by MechWOLLIer** [comment] 2017-04-20 18:37
I can confirm this, i have the same problem with Creators Update.

**Comment by dbaumeister** [comment] 2017-05-10 13:50
Merged in the PresentMon fix from 
https://github.com/GameTechDev/PresentMon/issues/25
--> This fixes the recordings on the Creators Update.

**Closed by dbaumeister** 2017-05-10 13:50 UTC
Labels: bug, verified

**Comment by larsonreever** [comment] 2017-05-24 11:14
i also have had the same problem with [Creators Update](http://driverrestore.com/windows-10-creators-update-new-features/).

**Comment by amddb** [comment] 2017-05-24 11:22
Hey @larsonreever, It would be really helpful to get more information on that issue, as I can't reproduce it with my current system setup.

1. On which games can you reproduce the issue?
2. Which setup are you running? - Running dxdiag and giving me its results would be perfect.
3. Can you give me the OCAT logfiles? (Documents/OCAT/Logs)

Thank you very much :)
