### ISSUE TITLE
This does not work at all!

### ISSUE THREAD

**Issue by LordRampantHump** [GPUOpen-Tools/OCAT#34] opened 2018-03-09 22:33 UTC
I tried 7 games in my steam lib and this did not show overlay at all. The only thing i could get the overlay on was obs!

**Comment by aurolou** [comment] 2018-03-12 08:05
Hi,

may I ask which version you tried? You can get the most current version [here](https://ci.appveyor.com/api/buildjobs/xpgfuwdrpqbdf745/artifacts/OCAT_1.1.0.125.exe). Could you please try this one out? We made a couple of changes and bug fixes since the last official release. If it still doesn't show any overlay, could you please describe the steps to reproduce your issue? Thanks! :)

**Comment by rys** [comment] 2018-12-13 19:14
User didn’t follow up with more information after 9 months and we’ve improved compatibility a lot since then. Closing.

**Closed by rys** 2018-12-13 19:14 UTC
