### ISSUE TITLE
Recordings not being created (DoomVK, Win10 CU)

### ISSUE THREAD

**Issue by silentdragoon** [GPUOpen-Tools/OCAT#20] opened 2017-07-11 00:35 UTC
The overlay is appearing fine in game (Doom Vulkan version), I can record using the hotkey and a summary appears briefly on screen, but no records appear in Documents / Ocat. 

The logs are attached, and say "Get module handle failed (gameoverlay64.dll) -  Error Code: 126 (The specified module could not be found.)"

Logs:

[GlobalHook64Log.txt](https://github.com/GPUOpen-Tools/OCAT/files/1137422/GlobalHook64Log.txt)
[PresentMonLog.txt](https://github.com/GPUOpen-Tools/OCAT/files/1137419/PresentMonLog.txt)
[gameoverlayLog.txt](https://github.com/GPUOpen-Tools/OCAT/files/1137420/gameoverlayLog.txt)
[GlobalHook32Log.txt](https://github.com/GPUOpen-Tools/OCAT/files/1137421/GlobalHook32Log.txt)

**Comment by amddb** [comment] 2017-07-11 08:30
Hey @silentdragoon, thanks for your input. Unfortunately I can not reproduce it on my machine.
Can you do me a favor and try to run PresentMon (https://github.com/GameTechDev/PresentMon) directly on Doom Vulkan?

**Comment by silentdragoon** [comment] 2017-07-11 14:01
I downloaded the latest Windows build of PresentMon from Github and ran it successfully. Here's the resultant CSV file, which seems fine to me: 

http://www.sharecsv.com/s/4bbec0b97002a45f3405b7eaa9b8cf70/PresentMon-DOOMx64vk.exe-2017-07-11T145316.csv

**Comment by amddb** [comment] 2017-07-11 14:10
Thanks a lot @silentdragoon . I'll take care of it :)

**Comment by silentdragoon** [comment] 2017-07-11 14:15
Thanks @amddb! Here are some more recent logs, showing the failed single application hook (maybe) and successful hook but not files written (both events from 15:00, with single first then global).

[GlobalHook32Log.txt](https://github.com/GPUOpen-Tools/OCAT/files/1139142/GlobalHook32Log.txt)
[GlobalHook64Log.txt](https://github.com/GPUOpen-Tools/OCAT/files/1139143/GlobalHook64Log.txt)
[PresentMonLog.txt](https://github.com/GPUOpen-Tools/OCAT/files/1139144/PresentMonLog.txt)
[gameoverlayLog.txt](https://github.com/GPUOpen-Tools/OCAT/files/1139145/gameoverlayLog.txt)

**Comment by amddb** [comment] 2017-07-11 14:22
Single application capture won't work with Doom Vulkan, as the application does the following things:
1. Start the OpenGL version <-- OCAT can successfully hook that
2. Start the Vulkan version <-- Is not recognized as we do not hook into child processes
3. Closes the OpenGL instance <-- OCAT stops capturing

So in a sense OCAT works as intended here.

**Comment by silentdragoon** [comment] 2017-07-11 14:38
Sure, that explains the non-hooking perfectly. Thanks for explaining. 👍 That just leaves the original bug, then :)

**Comment by rys** [comment] 2018-12-17 16:06
Closing due to issue age. Please create a new issue if you're still experiencing issues with game compatibility (this is tested to work OK at the moment).

**Closed by rys** 2018-12-17 16:06 UTC
Labels: api: vulkan, bug, not verified
